# Generated by Django 5.2.17 on 2026-08-21 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, default='Software Engineer', max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, default='San Francisco, CA', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=3)),
                ('preferred_roles', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('salary_expectation', models.CharField(blank=True, default='$120,000 - $160,000', max_length=100)),
                ('remote_preference', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('any', 'Any')], default='any', max_length=20)),
                ('resume', models.TextField(blank=True, help_text='Resume text or markdown summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='profiles', to='skills.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
