# Generated by Django 5.2.17 on 2026-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Programming Languages'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Databases'), ('cloud_devops', 'Cloud & DevOps'), ('ai_ml', 'AI & Machine Learning'), ('security', 'Security'), ('mobile', 'Mobile'), ('general', 'General')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
