# Generated by Django 5.2.17 on 2026-08-21 17:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(db_index=True, default='Engineering', max_length=100)),
                ('remote_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='remote', max_length=20)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Remote', 'Remote'), ('Internship', 'Internship')], db_index=True, default='Full-time', max_length=50)),
                ('experience_level', models.CharField(choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Lead', 'Lead')], db_index=True, default='Mid', max_length=50)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('salary', models.CharField(blank=True, default='$120,000 - $160,000', max_length=100)),
                ('application_url', models.URLField(blank=True, default='https://example.com/apply')),
                ('source', models.CharField(db_index=True, default='direct', max_length=100)),
                ('source_job_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='jobs', to='skills.skill')),
            ],
            options={
                'ordering': ['-posted_at', '-created_at'],
                'indexes': [models.Index(fields=['title', 'category', 'is_active'], name='jobs_job_title_60d748_idx'), models.Index(fields=['employment_type', 'experience_level', 'is_active'], name='jobs_job_employm_251aa5_idx'), models.Index(fields=['source', 'source_job_id'], name='jobs_job_source_ebd2a5_idx')],
            },
        ),
    ]
